project:
  type: book
  resources:
    - _media
  pre-render: find_crossrefs.py

book:
  title: "Data Science 1"
  author: "Tobin Driscoll"
  date: "January 2024"
  favicon: _media/logo_small.png
  cover-image: _media/logo.png
  chapters:
    - index.qmd
    - examples.qmd
    - resources.qmd
    - starting.qmd
    - data.qmd
    - stats.qmd
    - classification.qmd
    - selection.qmd
    - regression.qmd
    - clustering.qmd
    - networks.qmd
    # - references.qmd
  comments:
    hypothesis: true
  sidebar: 
    header: "![](_media/logo_small.png){height=120 fig-align='center'}"
    footer: "Copyright 2023 by Toby Driscoll"
  page-footer:
    left: 
      - text: "Data Science 1"
    right: 
      - text: "Toby Driscoll"
  downloads: [pdf]
# number-depth: 3

bibliography: references.bib

execute: 
  cache: true
  warning: false
  kernelspec:
    name: "python3"
    language: "python"
    display_name: "Python (datasci)"

format:
  html:
    theme: 
      - flatly
      - tweaks.scss
    # css: tweaks.css
    code-copy: true
    include-in-header: header.html
  pdf:
    papersize: letter
    include-in-header: _macros.tex
    geometry: 
      - top=1.5in
      - left=1.25in
      - right=1.25in
      - bottom=1.25in
    #   documentclass: scrreprt

# filters: 
#   - crossref-listings
